# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/cancunf-motcamera/setup-makefiles.sh

# SamSung_Camera App
PRODUCT_PACKAGES += \
    WingCam-N26 \
    Sec_CamMediaProvider \
    privapp_whitelist_com.sec.android.app.camera.xml \
    privapp-permissions-me.ayra.android.providers.media.xml

# Libs
PRODUCT_COPY_FILES += \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libanc_fullhdr.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libanc_fullhdr.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libaw_filter.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaw_filter.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libBSTAiScene.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBSTAiScene.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libBSTbase_share.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBSTbase_share.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libBSTBeauty.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBSTBeauty.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libBSTFoodMode.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBSTFoodMode.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libBSTHDRDETECT.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBSTHDRDETECT.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libBSTHdrDynamicJni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBSTHdrDynamicJni.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libBSTMultiExpoGainHDR.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBSTMultiExpoGainHDR.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libBSTSingleAIBokeh.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBSTSingleAIBokeh.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libBST_DualCalibration_Service.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libBST_DualCalibration_Service.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libaw_jni_face_detect.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaw_jni_face_detect.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libaw_jni_softenbeauty.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaw_jni_softenbeauty.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libaw_jni_sticker.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaw_jni_sticker.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libaw_soften.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libaw_soften.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libawfacesdk.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libawfacesdk.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libbst_mosaic.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libbst_mosaic.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libdualAfterSale.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libdualAfterSale.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libdualAfternative-lib.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libdualAfternative-lib.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libfacecls.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libfacecls.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libgre_api.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libgre_api.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libhwyuvtojpegencode.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libhwyuvtojpegencode.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libjniBstBeauty.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjniBstBeauty.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libjniBstFoodMode.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjniBstFoodMode.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libjniBstSingleBokeh.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjniBstSingleBokeh.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libjni_imageutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjni_imageutils.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libjni_yuv_encode.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjni_yuv_encode.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libjpeg_awturbo.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjpeg_awturbo.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libjpeg_qhturbo.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjpeg_qhturbo.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libloadfilter.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libloadfilter.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libpalmMobileDetectorFull.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libpalmMobileDetectorFull.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libqk3dsdk.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libqk3dsdk.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libSEF.quram.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libSEF.quram.so \
    vendor/samsung/wing-camera-n26/proprietary/system/lib64/libtensorflowlite.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libtensorflowlite.so


PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/wing-camera-26
